from typing import Protocol

from .drawing_api import DrawingAPI


class Game(Protocol):
    def load(self) -> None: ...
    def unload(self) -> None: ...
    def update(self, delta_time: float) -> None: ...
    def draw(self, drawer: DrawingAPI) -> None: ...
