from typing import Protocol


class Window(Protocol):
    def open_window(self, width: int, height: int, title: str) -> None: ...
    def is_open(self) -> bool: ...
    def close_window(self) -> None: ...
